spring:
  datasource:
      url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8
      username: root
      password: dengshuai
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver


server: 
  port: 8234
